name: 01-Basic-CI

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # actions/checkout@v4 = "Bring my repo code into the CI machine so I can work on it."

      - name: Print Info
        run: echo "CI Triggered"