name: 01-Basic-CI

on:
  push:
    branch:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Info
        run: echo "CI Triggered"