name: 04-Path-Based-Filter

on:
  push:
    branches:
      - main
    paths:
      - '**/*.txt'

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Info
        run: echo "Only .txt file modified in main branch root directory"