name: 08-Multi-Job

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Printing build
        run: echo "Build done"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Printing test
        run: echo "Test done"